### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kaito121855** [kaito121855/furima-31701#10]
＜自分のフリマアプリのURL＞
https://furima-31701.herokuapp.com/

＜Basic認証のIDとパスワード＞
ID　　　　　kaito
パスワード　5757

＜出品者用のメールアドレスとパスワード＞
メールアドレス　test1@test.com
パスワード　　　test1231

＜購入者用のメールアドレスとパスワード＞
メールアドレス　test2@test.com
パスワード　　　test1232

＜購入用カードの番号・期限・セキュリティコード＞
番号　　　　　　　4242424242424242
期限　　　　　　　2/22
セキリティコード　123

**Comment by mutorisa** [comment]
今野さん、ご提出ありがとうございます‼️
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正が依頼な項目]**

- [x] 商品購入ページでは、一覧や詳細ページで選択した商品の情報が出力されること
**→現在は、商品を購入する際、添付画像の通り一覧や商品詳細ページに表示されている商品とは別の商品画像が表示されてしまう状態です。**

<img width="873" alt="スクリーンショット 2020-11-19 14 07 00" src="https://user-images.githubusercontent.com/65144927/99624202-2841bd00-2a71-11eb-83d7-c28bc9f734e3.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kaito121855** [comment]
コメントありがとうございます！上記の通り訂正いたしましたので、確認お願いします！

＜修正内容＞
・商品購入画面の商品画像の表示

**Comment by mutorisa** [comment]
今野さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
